    
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: social-mdeia-web-argocd-application
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://github.com/lamthinhphat-kms/social-media-web.git
    targetRevision: HEAD
    path: argocd

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true